apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csa1
spec:
  selector:
    matchLabels:
      name: csa1
  template:
    metadata:
      labels:
        name: csa1
    spec:
      containers:
      - name: csa1
        image: eno931103/test:csa_test1
        imagePullPolicy: Always
        env:
        - name: CSA_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSA_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CSA_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CSA_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CSA_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: CSA_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: proc
          mountPath: /rootfs/proc
          readOnly: true
        - name: docker
          mountPath: /rootfs/docker
          readOnly: true
        - name: moby
          mountPath: /rootfs/moby
          readOnly: true
        - name: containers
          mountPath: /rootfs/containers
          readOnly: true
        - name: k8sio
          mountPath: /rootfs/k8s.io
          readOnly: true
        - name: snapshots
          mountPath: /rootfs/snapshots
          readOnly: true
        ports:
          - name: http
            hostPort: 8080
            containerPort: 8080
            protocol: TCP
        command: ["/dist/main"]
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: moby
        hostPath:
          path: /run/docker/runtime-runc/moby
      - name: containers
        hostPath:
          path: /var/lib/containers
      - name: k8sio
        hostPath:
          path: /run/containerd/io.containerd.runtime.v2.task/k8s.io
      - name: snapshots
        hostPath:
          path: /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots